# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Our Studios"
  pageRef = "games"
  weight = 10

[[main]]
  name = "Our services"
  pageRef = "services"
  weight = 15

[[main]]
  name = "Our content creators"
  pageRef = "content_creators"
  weight = 16

[[main]]
  name = "Friends"
  pageRef = "friends"
  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/cvga" # TBC
  weight = 200

[[main]]
  identifier = "mastodon"
  pre = "mastodon"
  url = "https://masto.ai/@cvga" # TBC
  weight = 300

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/abecam/CVGA"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20
